---
  - hosts: all
    tasks:
     - name: 1)
       community.general.parted: device=/dev/sdb unit=MiB
       register: sdb_info
       when: ansible_facts['devices']['sdb'] is defined
     
     - name: 2) 
       community.general.parted:
         device: /dev/sdb
         number: 1
         state: present
       when: ansible_facts['devices']['sdb'] is defined

     - name: Collect only facts returned by facter
       ansible.builtin.setup:

     - name: 3)
       community.general.lvg:
         vg: vgbackup
         pvs: /dev/sdb1
       when: ansible_facts['devices']['sdb']['partitions']['sdb1'] is defined

     - name: Collect only facts returned by facter
       ansible.builtin.setup:

     - name: 4)
       community.general.lvol:
         vg: vgbackup
         lv: lvbackup
         size: 1500
       when: 
         - ansible_facts['lvm']['vgs']['vgbackup'] is defined
         - sdb_info.disk.size > 1500

     - name: Collect only facts returned by facter
       ansible.builtin.setup:
      
     - name: 5)
       ansible.builtin.debug:
          msg: "Məntiqi həcm üçün kifayət qədər yer yoxdur"
       when:
         - ansible_facts['lvm']['vgs']['vgbackup'] is defined
         - sdb_info.disk.size < 1500
           
     - name: 6)
       community.general.lvol:
         vg: vgbackup
         lv: lvbackup
         size: 800
       when:
         - ansible_facts['lvm']['vgs']['vgbackup'] is defined
         - sdb_info.disk.size < 1500

     - name: Collect only facts returned by facter
       ansible.builtin.setup:

     - name: 7)
       ansible.builtin.debug:
          msg: "Cild qrupu mövcud deyil"
       when: ansible_facts['lvm']['vgs']['vgbackup'] is defined

     - name: 8)
       community.general.filesystem:
          fstype: xfs
          dev: /dev/vgbackup/lvbackup
       when: ansible_facts['lvm']['lvs']['lvbackup'] is defined

     - name: 9)
       ansible.posix.mount:
          path: /backup
          src: /dev/vgbackup/lvbackup
          fstype: xfs
          state: mount
       when: ansible_facts['lvm']['lvs']['lvbackup'] is defined
