---
  - name: hwreport-task
    hosts: all
    tasks:

      - name: 1)
        ansible.builtin.copy:
          src: /home/sandy/ansible/hardware-report
          dest: /root/hwreport.txt

      - name: 2)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^HOST='
          line: HOST= {{ansible_facts['hostname']}}

      - name: 3)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^IP='
          line: IP= {{ansible_facts['default_ipv4']['address'] | default ('NONE', True)}}

      - name: 4)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^PROCESSOR='
          line: PROCESSOR= {{ansible_facts['processor_cores'] | default ('NONE', True)}}

      - name: 5)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^MEMORY='
          line: MEMORY= {{ansible_facts['memtotal_mb'] | default ('NONE', True)}} MB

      - name: 6)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^KERNEL='
          line: KERNEL= {{ansible_facts['kernel'] | default ('NONE', True)}}


      - name: 7)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^BIOS='
          line: BIOS= {{ansible_facts['bios_version'] | default ('NONE', True)}}

      - name: 8)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^SDA_DISK_SIZE='
          line: SDA_DISK_SIZE= {{ansible_facts['devices']['sda']['size'] | default ('NONE', True)}}

      - name: 9)
        ansible.builtin.lineinfile:
          path: /root/hwreport.txt
          regexp: '^SDB_DISK_SIZE='
          line: SDB_DISK_SIZE= {{ansible_facts['devices']['sdb']['size'] | default ('NONE', True)}}