---
  - hosts: dev
    tasks:

        - ansible.builtin.user:
            name: webdev

        - ansible.builtin.file:
            path: /webdev
            owner: webdev
            state: directory
            mode: '2755'            

        - community.general.sefcontext:
            target: '/webdev(/.*)?'
            setype: httpd_sys_content_t
            state: present

        - ansible.builtin.command: restorecon -irv /webdev      

        - ansible.builtin.yum:
              name: httpd
              state: latest

        - ansible.builtin.copy:
            content: 'Development'
            dest: /webdev/index.html

        - ansible.builtin.file:
            src: /webdev
            dest: /var/www/html/webdev
            state: link      

        - ansible.builtin.systemd_service:
              name: httpd
              state: started
              enabled: true

        - ansible.posix.firewalld:
            service: "{{item}}"
            state: enabled
            permanent: true
            immediate: true
          loop:
            - http
            - https